defaults: &defaults
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  github_key: <%= ENV['GITHUB_KEY'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>


development:
  <<: *defaults
  secret_key_base: eee732c327e06b6562ffd2f109d4a9e8309ebe89799ea93b2d03e83479d97c693a041892c0c0ac9a8c5ed95ccbf0bc9f63aa98f5eac8ee69572e1ff7b4e98de8
  github_key: 1913f36a70df5e36386c
  github_secret: 5b6844c3daedaa0aa38df3685e308f4c69af2a67

production:
  <<: *defaults
